build = "npm run build"
artifact = "dist/main.js"
static = "out"

env = [
  "githubClientId",
  "allowedGithubUsers",
  { key = "icpBeian", optional = true },
  { key = "feedOrigin", optional = true },
]

secrets = [
  "githubClientSecret",
  "jwtSecretKey",
]

mysql = [
  "primary",
]
